# coding: utf-8

"""
    e-MCF

    DGI Bénin - Tous droits réservés  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.operator_dto import OperatorDto  # noqa: E501
from swagger_client.rest import ApiException


class TestOperatorDto(unittest.TestCase):
    """OperatorDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperatorDto(self):
        """Test OperatorDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.operator_dto.OperatorDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
