# coding: utf-8

"""
    e-MCF

    DGI Bénin - Tous droits réservés  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sfe_info_api import SfeInfoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSfeInfoApi(unittest.TestCase):
    """SfeInfoApi unit test stubs"""

    def setUp(self):
        self.api = SfeInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_info_invoice_types_get(self):
        """Test case for api_info_invoice_types_get

        """
        pass

    def test_api_info_payment_types_get(self):
        """Test case for api_info_payment_types_get

        """
        pass

    def test_api_info_status_get(self):
        """Test case for api_info_status_get

        """
        pass

    def test_api_info_tax_groups_get(self):
        """Test case for api_info_tax_groups_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
