# coding: utf-8

"""
    e-MCF

    DGI Bénin - Tous droits réservés  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sfe_invoice_api import SfeInvoiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSfeInvoiceApi(unittest.TestCase):
    """SfeInvoiceApi unit test stubs"""

    def setUp(self):
        self.api = SfeInvoiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_invoice_get(self):
        """Test case for api_invoice_get

        """
        pass

    def test_api_invoice_post(self):
        """Test case for api_invoice_post

        """
        pass

    def test_api_invoice_uid_cancel_put(self):
        """Test case for api_invoice_uid_cancel_put

        """
        pass

    def test_api_invoice_uid_confirm_put(self):
        """Test case for api_invoice_uid_confirm_put

        """
        pass

    def test_api_invoice_uid_get(self):
        """Test case for api_invoice_uid_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
