# coding: utf-8

"""
    e-MCF

    DGI Bénin - Tous droits réservés  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.payment_dto import PaymentDto  # noqa: E501
from swagger_client.rest import ApiException


class TestPaymentDto(unittest.TestCase):
    """PaymentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentDto(self):
        """Test PaymentDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.payment_dto.PaymentDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
